#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
IMAGE_REPO=${IMAGE_NAME%:*}
IMAGE_TAG=${IMAGE_NAME#*:}

MLFLOW_VERSION=${IMAGE_TAG%-*}
PYTHON_TAG=${IMAGE_TAG#*-}
PYTHON_VERSION=${PYTHON_TAG:6}

# Trigger build
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg PYTHON_VERSION=$PYTHON_VERSION \
             --build-arg MLFLOW_VERSION=$MLFLOW_VERSION \
             -t $DOCKER_REPO:${DOCKER_TAG//,/ -t $DOCKER_REPO:} .
